# Generated by Django 4.0.1 on 2022-01-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_l', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='test',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
