# Generated by Django 4.0.1 on 2022-01-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_l', '0002_test_create_date_test_update_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='T',
        ),
    ]
