# Generated by Django 4.0.1 on 2022-01-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_l', '0005_alter_user_age_alter_user_id_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'teacher'), (2, 'student'), (3, 'tourist')], default=3),
        ),
    ]
