# Generated by Django 4.0.1 on 2022-01-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_l', '0006_uploadfileform_user_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='test_user',
        ),
    ]
