# Generated by Django 4.0.1 on 2022-01-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_l', '0007_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no',
            field=models.CharField(default='1000154566', max_length=12, unique=True),
        ),
    ]
