# Generated by Django 4.0.1 on 2022-01-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_l', '0008_user_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
