# Generated by Django 4.0.1 on 2022-01-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_l', '0009_alter_user_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456', max_length=18),
        ),
    ]
