# Generated by Django 4.0.1 on 2022-01-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_l', '0012_remove_user_password_user_password_bcrypt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'super_user'), (2, 'teacher'), (3, 'student'), (4, 'tourist')], default=3),
        ),
    ]
