# Generated by Django 4.0.1 on 2022-01-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(max_length=12, unique=True)),
                ('role', models.SmallIntegerField(choices=[(1, 'super_user'), (2, 'teacher'), (3, 'student'), (4, 'tourist')], default=3)),
                ('name', models.CharField(default='', max_length=5, verbose_name='用户名')),
                ('age', models.IntegerField(default=0, verbose_name='用户年龄')),
                ('password_bcrypt', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(choices=[('1000001', '我的文献'), ('1000002', '浏览'), ('1000003', '回收站'), ('1000004', '添加用户'), ('1000005', '导入'), ('1000006', '权限修改')], max_length=7)),
                ('state', models.SmallIntegerField(choices=[(1, 'allow'), (2, 'forbid')])),
                ('icon', models.CharField(max_length=200, null=True)),
                ('user_menu', models.ManyToManyField(to='user.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(choices=[('2000001', '浏览我的文档'), ('2000002', '删除我的文档'), ('2000003', '修改自己文档'), ('2000004', '添加学生'), ('2000005', '添加教师'), ('2000006', '导入文档'), ('2000007', '权限修改')], max_length=7)),
                ('state', models.SmallIntegerField(choices=[(1, 'allow'), (2, 'forbid')])),
                ('icon', models.CharField(max_length=200, null=True)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.menu')),
                ('user_function', models.ManyToManyField(to='user.User')),
            ],
        ),
    ]
