# Generated by Django 4.0.1 on 2022-01-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(choices=[('浏览我的文档', '2000001'), ('删除我的文档', '2000002'), ('修改自己文档', '2000003'), ('添加学生', '2000004'), ('添加教师', '2000005'), ('导入文档', '2000006'), ('权限修改', '2000007')], max_length=7)),
                ('icon', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(choices=[('我的文献', '1000001'), ('浏览', '1000002'), ('回收站', '1000003'), ('添加用户', '1000004'), ('导入', '1000005'), ('权限修改', '1000006')], max_length=7)),
                ('icon', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(max_length=12, unique=True)),
                ('role', models.SmallIntegerField(choices=[(1, 'super_user'), (2, 'teacher'), (3, 'student'), (4, 'tourist')], default=3)),
                ('name', models.CharField(default='', max_length=5, verbose_name='用户名')),
                ('age', models.IntegerField(default=0, verbose_name='用户年龄')),
                ('password_bcrypt', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[('allow', 1), ('forbid', 2)])),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[('allow', 1), ('forbid', 2)])),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.function')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='user_menu',
            field=models.ManyToManyField(through='user.UserMenus', to='user.User'),
        ),
        migrations.AddField(
            model_name='function',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.menu'),
        ),
        migrations.AddField(
            model_name='function',
            name='user_function',
            field=models.ManyToManyField(through='user.UserFunctions', to='user.User'),
        ),
    ]
