# Generated by Django 4.0.1 on 2022-01-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_menu_id_function_menu_alter_function_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfunctions',
            name='state',
            field=models.SmallIntegerField(choices=[(1, 'allow'), (2, 'forbid')]),
        ),
        migrations.AlterField(
            model_name='usermenus',
            name='state',
            field=models.SmallIntegerField(choices=[(1, 'allow'), (2, 'forbid')]),
        ),
    ]
