# Generated by Django 4.0.1 on 2022-02-09 08:16

from django.db import migrations, models
import django.db.models.deletion
import user.model.PdfModel


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userfunctions_state_alter_usermenus_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('pdf_title', models.CharField(max_length=128)),
                ('periodical', models.CharField(max_length=100, null=True)),
                ('last_modify', models.CharField(max_length=50, null=True)),
                ('article_type', models.CharField(max_length=100, null=True)),
                ('pdf', models.FileField(upload_to=user.model.PdfModel.user_directory_path)),
                ('date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
