# Generated by Django 4.0.1 on 2022-02-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='date',
        ),
    ]
