# Generated by Django 4.0.1 on 2022-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_pdf_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='score',
            field=models.IntegerField(default=5, max_length=1),
        ),
    ]
