# Generated by Django 4.0.1 on 2022-02-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_pdf_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPdfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='pdf',
            name='user_collect',
            field=models.ManyToManyField(through='user.UserPdfs', to='user.User'),
        ),
        migrations.AlterField(
            model_name='function',
            name='code',
            field=models.CharField(choices=[('2000001', '浏览我的文档'), ('2000002', '删除我的文档'), ('2000003', '修改自己文档'), ('2000004', '添加学生'), ('2000005', '添加教师'), ('2000006', '导入文档'), ('2000007', '权限修改'), ('2000008', '恢复文档'), ('2000009', '浏览其他文献'), ('2000010', '读取收藏'), ('2000011', '删除收藏'), ('2000012', '添加收藏')], max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='code',
            field=models.CharField(choices=[('1000001', '我的文献'), ('1000002', '浏览'), ('1000003', '回收站'), ('1000004', '添加用户'), ('1000005', '导入'), ('1000006', '权限修改'), ('1000007', '收藏')], max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='score',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_upload', related_query_name='user_collect', to='user.user'),
        ),
        migrations.AddField(
            model_name='userpdfs',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pdf'),
        ),
        migrations.AddField(
            model_name='userpdfs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_collect', related_query_name='user_collect', to='user.user'),
        ),
    ]
