# Generated by Django 4.0.1 on 2022-04-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userviewhistory_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserViewHistory',
            new_name='UserHistory',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='user_pdf_history',
        ),
        migrations.AddField(
            model_name='pdf',
            name='user_history',
            field=models.ManyToManyField(through='user.UserHistory', to='user.User'),
        ),
    ]
