# Generated by Django 4.0.1 on 2022-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_userviewhistory_userhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no',
            field=models.CharField(max_length=12, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_bcrypt',
            field=models.CharField(max_length=150, verbose_name='密码(加密)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'admin'), (2, 'teacher'), (3, 'student'), (4, 'tourist')], default=3, verbose_name='角色'),
        ),
    ]
